const exampleCSV1 = [
  ["1", "2", "3", "4", "5"],
  ["The", "song", "remains", "the", "same."],
];

const exampleCSV2 = [
  [
    "ID",
    "Name",
    "Age",
    "City",
    "Country",
    "Job",
    "Salary",
    "Experience",
    "Department",
    "Email",
  ],
  [
    "1",
    "Alice",
    "25",
    "New York",
    "USA",
    "Engineer",
    "$80,000",
    "3 years",
    "R&D",
    "alice@example.com",
  ],
  [
    "2",
    "Bob",
    "30",
    "London",
    "UK",
    "Designer",
    "$70,000",
    "5 years",
    "UI/UX",
    "bob@example.com",
  ],
  [
    "3",
    "Charlie",
    "28",
    "Berlin",
    "Germany",
    "Developer",
    "$85,000",
    "4 years",
    "IT",
    "charlie@example.com",
  ],
  [
    "4",
    "David",
    "35",
    "Tokyo",
    "Japan",
    "Manager",
    "$95,000",
    "10 years",
    "Marketing",
    "david@example.com",
  ],
  [
    "5",
    "Eve",
    "22",
    "Paris",
    "France",
    "Intern",
    "$40,000",
    "1 year",
    "HR",
    "eve@example.com",
  ],
  [
    "6",
    "Frank",
    "32",
    "Sydney",
    "Australia",
    "Analyst",
    "$78,000",
    "6 years",
    "Finance",
    "frank@example.com",
  ],
  [
    "7",
    "Grace",
    "27",
    "Toronto",
    "Canada",
    "HR Specialist",
    "$68,000",
    "3 years",
    "HR",
    "grace@example.com",
  ],
  [
    "8",
    "Hank",
    "40",
    "San Francisco",
    "USA",
    "CTO",
    "$150,000",
    "15 years",
    "Tech",
    "hank@example.com",
  ],
  [
    "9",
    "Ivy",
    "29",
    "Amsterdam",
    "Netherlands",
    "Marketing Lead",
    "$88,000",
    "5 years",
    "Marketing",
    "ivy@example.com",
  ],
  [
    "10",
    "Jack",
    "31",
    "Dubai",
    "UAE",
    "Consultant",
    "$92,000",
    "8 years",
    "Business",
    "jack@example.com",
  ],
  [
    "11",
    "Kara",
    "26",
    "Singapore",
    "Singapore",
    "Data Scientist",
    "$90,000",
    "4 years",
    "AI",
    "kara@example.com",
  ],
  [
    "12",
    "Leo",
    "34",
    "Hong Kong",
    "China",
    "Product Manager",
    "$110,000",
    "9 years",
    "Product",
    "leo@example.com",
  ],
  [
    "13",
    "Mona",
    "24",
    "Madrid",
    "Spain",
    "Software Engineer",
    "$82,000",
    "2 years",
    "IT",
    "mona@example.com",
  ],
  [
    "14",
    "Nathan",
    "37",
    "Seoul",
    "South Korea",
    "Director",
    "$120,000",
    "12 years",
    "Operations",
    "nathan@example.com",
  ],
  [
    "15",
    "Olivia",
    "29",
    "Rome",
    "Italy",
    "Content Writer",
    "$55,000",
    "3 years",
    "Media",
    "olivia@example.com",
  ],
  [
    "16",
    "Paul",
    "33",
    "Los Angeles",
    "USA",
    "Game Developer",
    "$95,000",
    "7 years",
    "Gaming",
    "paul@example.com",
  ],
  [
    "17",
    "Quinn",
    "28",
    "Bangkok",
    "Thailand",
    "HR Manager",
    "$85,000",
    "6 years",
    "HR",
    "quinn@example.com",
  ],
  [
    "18",
    "Rachel",
    "30",
    "Johannesburg",
    "South Africa",
    "Architect",
    "$88,000",
    "5 years",
    "Design",
    "rachel@example.com",
  ],
  [
    "19",
    "Steve",
    "42",
    "Oslo",
    "Norway",
    "CEO",
    "$200,000",
    "18 years",
    "Management",
    "steve@example.com",
  ],
  [
    "20",
    "Tina",
    "27",
    "Mumbai",
    "India",
    "Support Engineer",
    "$60,000",
    "4 years",
    "Customer Support",
    "tina@example.com",
  ],
];

const exampleCSV3 = [
  ["ID", "Name", "Age", "City", "Country"],
  ["1", "Alice", "25", "New York", "USA"],
  ["2", "Bob", "30", "London", "UK"],
  ["3", "Charlie", "28", "Berlin", "Germany"],
  ["4", "David", "35", "Tokyo", "Japan"],
  ["5", "Eve", "22", "Paris", "France"],
];

const exampleCSVForGraph = [
  ["ID", "Value"],
  ["1", "10"],
  ["2", "9"],
  ["14", "5"],
  ["12", "13"],
  ["11", "11"],
  ["109", "2"],
  ["143", "17"],
  ["hello", "8"],
  ["0", "1"],
  ["g53oiehwp5oinh", "22"],
];

const longExampleCSVForGraph = [
  ["ID", "Value"],
  ["1", "10"],
  ["2", "9"],
  ["14", "5"],
  ["12", "13"],
  ["11", "11"],
  ["109", "2"],
  ["143", "17"],
  ["hello", "8"],
  ["0", "1"],
  ["g53oiehwp5oinh", "22"],
  ["X123", "15"],
  ["42", "3"],
  ["a5b6", "20"],
  ["alpha", "7"],
  ["7a6f", "4"],
  ["zeta", "10"],
  ["g543", "18"],
  ["z89", "6"],
  ["ccc", "12"],
  ["dog", "9"],
  ["l33t", "17"],
  ["789", "13"],
  ["2bb8", "8"],
  ["m4x", "21"],
  ["54321", "11"],
  ["jkl", "14"],
  ["h92", "16"],
  ["abc123", "2"],
  ["test", "20"],
  ["bravo", "10"],
  ["chi", "4"],
  ["delta", "5"],
  ["emma", "11"],
  ["fish123", "8"],
  ["john_doe", "19"],
  ["hello_world", "3"],
  ["w1n5", "7"],
  ["s1n6", "12"],
  ["code123", "14"],
  ["random_str", "5"],
  ["val123", "15"],
  ["1000", "8"],
  ["level99", "18"],
  ["s0meid", "6"],
  ["endoflist", "10"],
];

const emptyCSV: string[] = [];

const nullCSV = null;

const availableData = [
  ["Dataset Name", "Filepath"],
  ["Empty", "data/empty.csv"],
  ["DOL RI Earnings Disparity", "data/census/dol_ri_earnings_disparity.csv"],
  ["Postsecondary Education", "data/census/postsecondary_education.csv"],
  ["RI Town Income Dataset", "data/census/RI-Town-Income-Dataset.csv"],
  ["Malformed Signs", "data/malformed/malformed_signs.csv"],
  ["Malformed Stars", "data/malformed/malformed_stars.csv"],
  ["Regex Breaker", "data/malformed/regex-breaker.csv"],
  ["Star Data", "data/stars/stardata.csv"],
  ["Ten Star", "data/stars/ten-star.csv"],
  ["Ten Star Blank Header", "data/stars/ten_star_blank_header.csv"],
  ["Ten Star No Header", "data/stars/ten_star_no_headers.csv"],
  ["Graphable Data", "data/graphable-data.csv"],
];

export function getParsedTable(
  tableName: string
): string[][] | string[] | null {
  switch (tableName) {
    case "Sample Table 1": {
      return exampleCSV1;
    }
    case "Sample Table 2": {
      return exampleCSV2;
    }
    case "Sample Table 3": {
      return exampleCSV3;
    }
    case "Sample Table For Graph": {
      return exampleCSVForGraph;
    }
    case "Large Sample Table For Graph": {
      return longExampleCSVForGraph;
    }
    case "Empty Table": {
      return emptyCSV;
    }
    case "Null Table": {
      return nullCSV;
    }
  }
  return null;
}

export function getAvailableDataTable() {
  return availableData;
}
